console.info('第一次的功能开发')
console.info('第二次的功能开发第一次提交')
console.info('第二次的功能开发第二次提交')
console.info('第二次的功能开发第三次提交')
console.info('这是一个bug修复')
console.info('又一个bug被修复了')
console.info('我是通过bugfix修复的bug')